services:
  db:
    image: postgres:16.2-alpine
    restart: always
    environment:
      - TZ=UTC
      - PGTZ=UTC
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'